In [2]:
import numpy as np

# 1. Creating arrays
arr1d = np.array([10, 20, 30, 40, 50])
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("1D Array:", arr1d)
print("2D Array:\n", arr2d)
print("Shape of 2D array:", arr2d.shape)

# 2. Indexing and slicing
print("\nFirst element of 1D array:", arr1d[0])
print("Last element:", arr1d[-1])
print("Slice [1:4]:", arr1d[1:4])
print("Element at row 1, col 2 of 2D array:", arr2d[1, 2])

# 3. Mathematical operations
print("\nArray + 10:", arr1d + 10)
print("Array * 2:", arr1d * 2)
print("Sum of array:", np.sum(arr1d))
print("Mean of array:", np.mean(arr1d))
print("Max value:", np.max(arr1d))
print("Min value:", np.min(arr1d))

# 4. Array-based calculation example
prices = np.array([100, 250, 400, 600, 900])
discount = prices * 0.10   # 10% discount
final_prices = prices - discount
print("\nOriginal prices:", prices)
print("Discount amounts:", discount)
print("Final prices after discount:", final_prices)

1D Array: [10 20 30 40 50]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of 2D array: (3, 3)

First element of 1D array: 10
Last element: 50
Slice [1:4]: [20 30 40]
Element at row 1, col 2 of 2D array: 6

Array + 10: [20 30 40 50 60]
Array * 2: [ 20  40  60  80 100]
Sum of array: 150
Mean of array: 30.0
Max value: 50
Min value: 10

Original prices: [100 250 400 600 900]
Discount amounts: [10. 25. 40. 60. 90.]
Final prices after discount: [ 90. 225. 360. 540. 810.]
